name: React Template CI
on:
  pull_request:
    branches: [master]
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Get Threshold
        id: threshold
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'jest.config.json'
          prop_path: 'coverageThreshold.global.statements'

      - name: Test and Check total line coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          threshold: ${{steps.threshold.outputs.prop}}

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG}}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
