name: Jest Coverage Report with Annotations (CI)
on:
  pull_request:
    branches:
      - master
      - 'push-action/**'
jobs:
  coverage_report:
    name: Jest Coverage Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Get Threshold
        id: threshold
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'jest.config.json'
          prop_path: 'coverageThreshold.global.statements'
      - name: Test and generate coverage report
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: ${{steps.threshold.outputs.prop}}
          package-manager: yarn
          custom-title: Jest Coverage Report

  create_badges:
    name: Create Badges
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
      - name: Set branch name
        id: vars
        run: echo ::set-output name=stage::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})
      - name: Install dependencies
        run: yarn install
      - name: Create badges
        run: yarn run test:badges
      - name: Commit badges
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Gitflow
          author_email: git@wednesday.is
          message: 'Update badges'
          add: 'badges/'
          push: false
      - name: Pushing to a protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: ${{ steps.vars.outputs.stage }}
          unprotect_reviews: true
